# Generated by Django 3.2.25 on 2025-04-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_hora_creacion_publicacion_hora_publicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='fecha_creacion',
            new_name='fecha_publicacion',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='hora_publicacion',
            new_name='hora_creacion',
        ),
    ]
