# Generated by Django 3.2.25 on 2025-04-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20250421_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='hora_creacion',
            new_name='fecha_creacion',
        ),
    ]
